#!/usr/bin/env python3
"""
Generate per-source `LICENSE.md` and `SOURCE.md` files in the new
`sources/<source>/` layout, plus a top-level `sources/_index.json`
describing the new structure.

Run AFTER `scripts/stamp_and_reorg.py`.
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES_DIR = ROOT / "data" / "datasets" / "buckets" / "sources"
BUCKETS_DIR = ROOT / "data" / "datasets" / "buckets"
RIGHTS_CONTACT = "see data/REMOVAL.md"

SOURCE_DESCRIPTIONS: dict[str, dict] = {
    "atomic-red-team": {
        "display": "Atomic Red Team (Red Canary)",
        "summary": "Community-driven library of tests mapped to MITRE ATT&CK. Each test is a small, safe-to-run adversary emulation: command, input arguments, expected detection artifact, cleanup.",
        "use_case": "Exact commands, expected artifacts, and cleanup for ~700 ATT&CK techniques.",
        "risk": "low",
        "upstream_url": "https://github.com/redcanaryco/atomic-red-team",
    },
    "mitre-stockpile": {
        "display": "MITRE Caldera — Stockpile",
        "summary": "Plugin-based TTP descriptors for the MITRE Caldera adversary emulation platform. YAML-defined abilities with executor, command, and parser sections.",
        "use_case": "Adversary emulation ability triples (YAML-defined TTP descriptors).",
        "risk": "low",
        "upstream_url": "https://github.com/mitre/stockpile",
    },
    "mitre-atlas-arsenal": {
        "display": "MITRE ATLAS Arsenal",
        "summary": "Adversary tactics for AI systems — case studies and evaluations of real attacks against machine learning systems.",
        "use_case": "Adversarial ML case studies and evaluation harnesses.",
        "risk": "low",
        "upstream_url": "https://github.com/mitre-atlas/arsenal",
    },
    "metasploit-framework": {
        "display": "Metasploit Framework (Rapid7)",
        "summary": "The world's most widely used penetration testing framework. 8,349 module descriptions, options, references, and payloads converted to training triples.",
        "use_case": "Module descriptions, options, references, payloads — converted to 'what this module does' triples.",
        "risk": "medium",
        "risk_note": "BSD-3-Clause attribution. Each record is stamped with `license: BSD-3-Clause` and `license_uri`. Do not strip these fields when redistributing.",
        "upstream_url": "https://github.com/rapid7/metasploit-framework",
    },
    "nvidia-garak": {
        "display": "garak (NVIDIA)",
        "summary": "LLM vulnerability scanner. Probes for hallucinations, data leakage, prompt injection, misinformation, toxicity, and jailbreaks.",
        "use_case": "DAN/probe JSON & TXT resources for AI red-teaming.",
        "risk": "low",
        "upstream_url": "https://github.com/NVIDIA/garak",
    },
    "azure-pyrit": {
        "display": "PyRIT (Azure)",
        "summary": "Python Risk Identification Tool for generative AI. Orchestrates automated red-teaming of LLM endpoints.",
        "use_case": "Jailbreak template definitions (no records currently in dataset; slot reserved for future).",
        "risk": "low",
        "upstream_url": "https://github.com/Azure/PyRIT",
    },
    "cyberark-fuzzyai": {
        "display": "FuzzyAI (CyberArk)",
        "summary": "Automated AI jailbreak framework that uses fuzzing to find prompt-injection bypasses.",
        "use_case": "Adversarial prompt resources (no records currently in dataset; slot reserved for future).",
        "risk": "low",
        "upstream_url": "https://github.com/cyberark/FuzzyAI",
    },
    "promptfoo": {
        "display": "promptfoo",
        "summary": "Open-source LLM evaluation and red-teaming framework. Defines TypeScript plugin-based adversarial prompts.",
        "use_case": "Red-team TypeScript plugin definitions for prompt injection.",
        "risk": "low",
        "upstream_url": "https://github.com/promptfoo/promptfoo",
    },
    "promptmap": {
        "display": "promptmap (utkusen)",
        "summary": "Prompt injection scanner with a YAML rule file format. Tests an LLM endpoint against a curated set of injection attacks.",
        "use_case": "Prompt injection YAML rule files.",
        "risk": "low",
        "upstream_url": "https://github.com/utkusen/promptmap",
    },
    "llm-generated": {
        "display": "LLM-generated (qwen2.5-coder-14b-instruct via LMStudio)",
        "summary": "Synthetic ATT&CK technique records generated by the qwen2.5-coder-14b-instruct-uncensored model running locally via LMStudio. Each record was generated at temperature 0.4 against a category-specific prompt with few-shot examples.",
        "use_case": "Fills gaps in deterministic synthetic coverage; some duplication and quality issues have been documented.",
        "risk": "low",
        "risk_note": "Output of an LLM, not human-authored. GPL-3.0 licensed per the Qwen license terms. Quality varies; see data/audit_report.json for source coverage statistics.",
        "upstream_url": "https://github.com/QwenLM/Qwen2.5-Coder",
    },
    "attacklm-synthetic": {
        "display": "AttackLM Synthetic (deterministic templates + in-repo generation)",
        "summary": "Records generated by deterministic AttackLM scripts in `scripts/generate_*.py` and `scripts/generate_synthetic_scarce.py`. Templates follow a fixed structure with curated examples; output is reproducible.",
        "use_case": "Augments and diversifies upstream coverage. Used in 12+ buckets across MITRE tactics and AI security.",
        "risk": "low",
        "upstream_url": "https://github.com/Veedubin/AttackLM",
    },
}


def main():
    sources_index: list[dict] = []
    per_source_counts: Counter = Counter()

    for src_dir in sorted(SOURCES_DIR.iterdir()):
        if not src_dir.is_dir() or src_dir.name.startswith("_"):
            continue
        source_name = src_dir.name
        desc = SOURCE_DESCRIPTIONS.get(
            source_name,
            {
                "display": source_name,
                "summary": "(no description)",
                "use_case": "",
                "risk": "unknown",
                "upstream_url": "",
            },
        )

        # Count records in this source. Each source can have either:
        #   - <bucket>/<tactic>/data.jsonl  (3 levels: e.g. base/execution/data.jsonl)
        #   - <bucket>/data.jsonl            (2 levels: e.g. orchestrator/data.jsonl)
        n_records = 0
        per_bucket = []
        seen_dirs: set[Path] = set()
        for jsonl in sorted(src_dir.rglob("*.jsonl")):
            parts = jsonl.relative_to(src_dir).parts
            if len(parts) == 3:
                # <bucket>/<tactic>/<file>
                bucket_name = f"{parts[0]}/{parts[1]}"
                bucket_dir = jsonl.parent
            elif len(parts) == 2:
                # <bucket>/<file>  (e.g. orchestrator/data.jsonl)
                bucket_name = parts[0]
                bucket_dir = jsonl.parent
            else:
                continue
            n = sum(1 for _ in jsonl.open())
            n_records += n
            # Aggregate into per-bucket totals
            for entry in per_bucket:
                if entry["_dir"] == bucket_dir:
                    entry["files"][jsonl.name] = n
                    entry["total"] += n
                    break
            else:
                per_bucket.append(
                    {
                        "_dir": bucket_dir,
                        "bucket": bucket_name,
                        "files": {jsonl.name: n},
                        "total": n,
                    }
                )
        # Drop internal _dir
        for entry in per_bucket:
            entry.pop("_dir", None)
        per_source_counts[source_name] = n_records

        # Sample record to extract license/license_uri
        sample_license = ""
        sample_license_uri = ""
        for jsonl in src_dir.rglob("*.jsonl"):
            with jsonl.open() as f:
                for line in f:
                    rec = json.loads(line)
                    sample_license = rec.get("license", "")
                    sample_license_uri = rec.get("license_uri", "")
                    break
            if sample_license:
                break

        # Write LICENSE.md
        license_md = f"""# {desc["display"]} — License

| Field | Value |
|---|---|
| **Source** | {desc["display"]} |
| **Upstream** | {desc["upstream_url"]} |
| **License** | {sample_license} |
| **License URI** | {sample_license_uri} |
| **Records** | {n_records} |
| **Risk level** | {desc["risk"]} |
| **Rights holder contact** | {RIGHTS_CONTACT} |

## License text

The upstream `{desc["display"]}` project is released under the **{sample_license}** license.
The full license text is available at:
<{sample_license_uri}>

## What this directory contains

This directory holds the records derived from `{desc["display"]}`. Every
record carries the following provenance fields:

- `source`: the canonical source name (e.g. `atomic-red-team`)
- `source_uri`: link to the upstream project
- `license`: SPDX license identifier (e.g. `MIT`, `Apache-2.0`)
- `license_uri`: link to the full license text
- `rights_contact`: pointer to the rights-holder contact process

**Do not strip these fields** when re-distributing.

## Per-bucket breakdown

| Bucket | File | Records |
|---|---:|---:|
"""
        for b in per_bucket:
            for fname, cnt in b["files"].items():
                license_md += f"| {b['bucket']} | `{fname}` | {cnt} |\n"
        license_md += f"| **TOTAL** | | **{n_records}** |\n"

        (src_dir / "LICENSE.md").write_text(license_md)

        # Write SOURCE.md (narrative description)
        risk_section = ""
        if desc.get("risk_note"):
            risk_section = f"\n## Risk note\n\n{desc['risk_note']}\n"

        source_md = f"""# {desc["display"]}

{desc["summary"]}

## What it's used for

{desc["use_case"]}

## Provenance

| Field | Value |
|---|---|
| **Source name** | `{source_name}` |
| **Display name** | {desc["display"]} |
| **Upstream** | <{desc["upstream_url"]}> |
| **License** | {sample_license} |
| **Risk level** | {desc["risk"]} |
{risk_section}
## How it's ingested

The records in this directory are produced by
`scripts/stamp_and_reorg.py`, which reads from
`data/datasets/buckets/<bucket>/` and writes here.

To re-run: `uv run python scripts/stamp_and_reorg.py`

## Rights-holder contact

If you are a rights holder for `{desc["display"]}` and would like any of
these records removed, see **`data/REMOVAL.md`** at the repository root.
Removal is fast and unconditional.
"""
        (src_dir / "SOURCE.md").write_text(source_md)

        sources_index.append(
            {
                "name": source_name,
                "display": desc["display"],
                "license": sample_license,
                "license_uri": sample_license_uri,
                "upstream_url": desc["upstream_url"],
                "risk": desc["risk"],
                "n_records": n_records,
                "buckets": per_bucket,
            }
        )

    # Write _index.json
    index = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_sources": len(sources_index),
        "total_records": sum(s["n_records"] for s in sources_index),
        "sources": sources_index,
    }
    (SOURCES_DIR / "_index.json").write_text(json.dumps(index, indent=2))

    # Write top-level README.md
    readme = f"""# AttackLM Training Data — Per-Source Layout

This directory is the **canonical** layout for the AttackLM training data.
Records are organized by upstream **source** first, then by bucket.

## Layout

```
sources/
├── _index.json                  # machine-readable manifest
├── atomic-red-team/             # MIT — Red Canary
├── mitre-stockpile/             # Apache-2.0 — MITRE Caldera
├── mitre-atlas-arsenal/         # Apache-2.0 — MITRE ATLAS
├── metasploit-framework/        # BSD-3-Clause — Rapid7 (medium risk: attribution required)
├── nvidia-garak/                # Apache-2.0 — NVIDIA
├── azure-pyrit/                 # MIT — Azure (slot reserved, no records yet)
├── cyberark-fuzzyai/            # Apache-2.0 — CyberArk (slot reserved, no records yet)
├── promptfoo/                   # MIT
├── promptmap/                   # MIT — utkusen
├── llm-generated/               # GPL-3.0 — qwen2.5-coder-14b output
└── attacklm-synthetic/          # MIT — in-repo deterministic templates
```

Each source directory contains:
- `LICENSE.md` — the license, license URI, per-bucket record counts
- `SOURCE.md` — narrative description, use case, risk note
- `<bucket>/<tactic>/data.jsonl` (and `data_synth.jsonl`, `data_llm.jsonl`
  where applicable)

## Why this layout

The previous flat layout (`data/datasets/buckets/<bucket>/data.jsonl`) made
attribution ambiguous: a single bucket could mix MIT, Apache-2.0, BSD-3, and
in-repo synthetic records, and the per-record `source` field was the only
way to disambiguate.

The per-source layout:
1. **Makes attribution unambiguous** — every record in `metasploit-framework/`
   is BSD-3-Clause, every record in `atomic-red-team/` is MIT, etc.
2. **Simplifies license compliance** — re-distributors can drop an entire
   source by deleting one directory.
3. **Simplifies rights-holder removal** — `data/REMOVAL.md` requests are
   answered by deleting one directory.
4. **Preserves the per-tactic bucket structure** — each source still has
   `<bucket>/<tactic>/data.jsonl` so training scripts that consume by
   tactic continue to work.

## High-risk sources (NOT in this directory)

The following sources have been moved to `archive/restricted-sources/`
(per `data/ATTRIBUTION.md` license review 2026-06-11) and are **excluded**
from the public dataset:

| Source | License | Reason |
|---|---|---|
| endgameinc/RTA | AGPL-3.0 | Viral copyleft |
| guardicore/infection_monkey | GPL-3.0 | Viral copyleft |
| TheBigPromptLibrary | mixed/unclear | Copyright laundering of leaked prompts |

The data is preserved locally for the user's private research. See
`archive/restricted-sources/README.md` for details.

## Migration

The flat layout at `data/datasets/buckets/<bucket>/` is no longer the
canonical source. Training scripts and the audit tool should be updated to
read from `data/datasets/buckets/sources/<source>/...`.

The manifest at `data/datasets/buckets/manifest.json` is regenerated from
this directory by `scripts/rebuild_manifest.py`.

## Provenance stamp

Every record in this directory carries these fields (added by
`scripts/stamp_and_reorg.py`):

```json
{{
  "source": "atomic-red-team",
  "source_uri": "https://github.com/redcanaryco/atomic-red-team",
  "license": "MIT",
  "license_uri": "https://opensource.org/licenses/MIT",
  "rights_contact": "see data/REMOVAL.md"
}}
```

These fields are written by the ETL pipeline and **must not be stripped**
by downstream re-distributors.

## Total record count

{sum(s["n_records"] for s in sources_index):,} records across {len(sources_index)} sources.
"""
    (SOURCES_DIR / "README.md").write_text(readme)

    # Summary
    print(f"\n=== Per-source layout generated ===\n")
    for s in sources_index:
        print(
            f"  {s['name']:<25} {s['license']:<15} {s['n_records']:>6} records  ({s['risk']} risk)"
        )
    print(f"\nTotal: {sum(s['n_records'] for s in sources_index):,} records")
    print(f"Index: {SOURCES_DIR / '_index.json'}")


if __name__ == "__main__":
    main()
